---
name: Build
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/*
  pull_request:
jobs:
  yamllint:
    uses: dropwizard/workflows/.github/workflows/yamllint.yml@0ec34841b1d93de4fccd86a3a9112f331a65a01f # main
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
    uses: dropwizard/workflows/.github/workflows/maven.yml@0ec34841b1d93de4fccd86a3a9112f331a65a01f # main
    secrets: inherit
    with:
      java-version: ${{ matrix.java-version }}
