---
name: Build
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/*
  pull_request:
jobs:
  yamllint:
    uses: dropwizard/workflows/.github/workflows/yamllint.yml@608d5ce4a4b37f79f5acceae7c6598f5f548e12a # main
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
    uses: dropwizard/workflows/.github/workflows/maven.yml@608d5ce4a4b37f79f5acceae7c6598f5f548e12a # main
    secrets: inherit
    with:
      java-version: ${{ matrix.java-version }}
