---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - dropwizard-flyway-*
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@93997a2486261076390b4e02de3f52c625c8df87 # main
    secrets: inherit
