---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - dropwizard-flyway-*
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@fd38a7d9028b8d6c3f88360f017add78e7d5b5fd # main
    secrets: inherit
