---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - dropwizard-flyway-*
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@main
    secrets: inherit
