---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - dropwizard-flyway-*
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@608d5ce4a4b37f79f5acceae7c6598f5f548e12a # main
    secrets: inherit
